# This is a basic workflow to help you get started with Actions

name: Compile as pdf

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  latex_compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile main.tex
        uses: dante-ev/latex-action@master
        with:
          root_file:  main.tex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Push compilation results
        run: |
          git config --global user.name 'Eduardo'
          git config --global user.email 'edu.pignatelli@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          mv main.aux latex.out/
          mv main.bbl latex.out/
          mv main.blg latex.out/
          mv main.fdb_latexmk latex.out/
          mv main.fls latex.out/
          mv main.log latex.out/
          mv main.out latex.out/
          mv main.pdf latex.out/
          git add -f latex.out
          git commit -m "Automated latex compilation"
          git push
